# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raca',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='raca',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='P', max_length=1),
        ),
    ]
