# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racas', '0003_auto_20230622_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='cores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='raca',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
